/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Aboutpage,
    AboutpageFromJSON,
    AboutpageToJSON,
    NewAboutpage,
    NewAboutpageFromJSON,
    NewAboutpageToJSON,
} from '../models';

export interface AboutpageGetRequest {
    limit?: number;
    sort?: string;
    start?: number;
    ne?: string;
    lt?: string;
    lte?: string;
    gt?: string;
    gte?: string;
    contains?: string;
    containss?: string;
    _in?: Array<string>;
    nin?: Array<string>;
}

export interface AboutpagePutRequest {
    newAboutpage: NewAboutpage;
}

/**
 * 
 */
export class AboutpageApi extends runtime.BaseAPI {

    /**
     * Delete a single aboutpage record
     */
    async aboutpageDeleteRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/aboutpage`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Delete a single aboutpage record
     */
    async aboutpageDelete(initOverrides?: RequestInit): Promise<number> {
        const response = await this.aboutpageDeleteRaw(initOverrides);
        return await response.value();
    }

    /**
     * Find all the aboutpage\'s records
     */
    async aboutpageGetRaw(requestParameters: AboutpageGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Aboutpage>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['_limit'] = requestParameters.limit;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['_sort'] = requestParameters.sort;
        }

        if (requestParameters.start !== undefined) {
            queryParameters['_start'] = requestParameters.start;
        }

        if (requestParameters.ne !== undefined) {
            queryParameters['_ne'] = requestParameters.ne;
        }

        if (requestParameters.lt !== undefined) {
            queryParameters['_lt'] = requestParameters.lt;
        }

        if (requestParameters.lte !== undefined) {
            queryParameters['_lte'] = requestParameters.lte;
        }

        if (requestParameters.gt !== undefined) {
            queryParameters['_gt'] = requestParameters.gt;
        }

        if (requestParameters.gte !== undefined) {
            queryParameters['_gte'] = requestParameters.gte;
        }

        if (requestParameters.contains !== undefined) {
            queryParameters['_contains'] = requestParameters.contains;
        }

        if (requestParameters.containss !== undefined) {
            queryParameters['_containss'] = requestParameters.containss;
        }

        if (requestParameters._in) {
            queryParameters['_in'] = requestParameters._in;
        }

        if (requestParameters.nin) {
            queryParameters['_nin'] = requestParameters.nin;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/aboutpage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AboutpageFromJSON(jsonValue));
    }

    /**
     * Find all the aboutpage\'s records
     */
    async aboutpageGet(requestParameters: AboutpageGetRequest, initOverrides?: RequestInit): Promise<Aboutpage> {
        const response = await this.aboutpageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a single aboutpage record
     */
    async aboutpagePutRaw(requestParameters: AboutpagePutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Aboutpage>> {
        if (requestParameters.newAboutpage === null || requestParameters.newAboutpage === undefined) {
            throw new runtime.RequiredError('newAboutpage','Required parameter requestParameters.newAboutpage was null or undefined when calling aboutpagePut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/aboutpage`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NewAboutpageToJSON(requestParameters.newAboutpage),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AboutpageFromJSON(jsonValue));
    }

    /**
     * Update a single aboutpage record
     */
    async aboutpagePut(requestParameters: AboutpagePutRequest, initOverrides?: RequestInit): Promise<Aboutpage> {
        const response = await this.aboutpagePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
