/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Article,
    ArticleFromJSON,
    ArticleToJSON,
    NewArticle,
    NewArticleFromJSON,
    NewArticleToJSON,
} from '../models';

export interface ArticlesGetRequest {
    limit?: number;
    sort?: string;
    start?: number;
    ne?: string;
    lt?: string;
    lte?: string;
    gt?: string;
    gte?: string;
    contains?: string;
    containss?: string;
    _in?: Array<string>;
    nin?: Array<string>;
}

export interface ArticlesIdDeleteRequest {
    id: string;
}

export interface ArticlesIdPutRequest {
    id: string;
    newArticle: NewArticle;
}

export interface ArticlesPostRequest {
    newArticle: NewArticle;
}

export interface ArticlesSlugGetRequest {
    slug: string;
}

/**
 * 
 */
export class ArticleApi extends runtime.BaseAPI {

    /**
     */
    async articlesCountGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/articles/count`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async articlesCountGet(initOverrides?: RequestInit): Promise<object> {
        const response = await this.articlesCountGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async articlesGetRaw(requestParameters: ArticlesGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Article>>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['_limit'] = requestParameters.limit;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['_sort'] = requestParameters.sort;
        }

        if (requestParameters.start !== undefined) {
            queryParameters['_start'] = requestParameters.start;
        }

        if (requestParameters.ne !== undefined) {
            queryParameters['_ne'] = requestParameters.ne;
        }

        if (requestParameters.lt !== undefined) {
            queryParameters['_lt'] = requestParameters.lt;
        }

        if (requestParameters.lte !== undefined) {
            queryParameters['_lte'] = requestParameters.lte;
        }

        if (requestParameters.gt !== undefined) {
            queryParameters['_gt'] = requestParameters.gt;
        }

        if (requestParameters.gte !== undefined) {
            queryParameters['_gte'] = requestParameters.gte;
        }

        if (requestParameters.contains !== undefined) {
            queryParameters['_contains'] = requestParameters.contains;
        }

        if (requestParameters.containss !== undefined) {
            queryParameters['_containss'] = requestParameters.containss;
        }

        if (requestParameters._in) {
            queryParameters['_in'] = requestParameters._in;
        }

        if (requestParameters.nin) {
            queryParameters['_nin'] = requestParameters.nin;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/articles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ArticleFromJSON));
    }

    /**
     */
    async articlesGet(requestParameters: ArticlesGetRequest, initOverrides?: RequestInit): Promise<Array<Article>> {
        const response = await this.articlesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a record
     */
    async articlesIdDeleteRaw(requestParameters: ArticlesIdDeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling articlesIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/articles/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Delete a record
     */
    async articlesIdDelete(requestParameters: ArticlesIdDeleteRequest, initOverrides?: RequestInit): Promise<number> {
        const response = await this.articlesIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a record
     */
    async articlesIdPutRaw(requestParameters: ArticlesIdPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Article>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling articlesIdPut.');
        }

        if (requestParameters.newArticle === null || requestParameters.newArticle === undefined) {
            throw new runtime.RequiredError('newArticle','Required parameter requestParameters.newArticle was null or undefined when calling articlesIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/articles/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NewArticleToJSON(requestParameters.newArticle),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArticleFromJSON(jsonValue));
    }

    /**
     * Update a record
     */
    async articlesIdPut(requestParameters: ArticlesIdPutRequest, initOverrides?: RequestInit): Promise<Article> {
        const response = await this.articlesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new record
     */
    async articlesPostRaw(requestParameters: ArticlesPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Article>> {
        if (requestParameters.newArticle === null || requestParameters.newArticle === undefined) {
            throw new runtime.RequiredError('newArticle','Required parameter requestParameters.newArticle was null or undefined when calling articlesPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/articles`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewArticleToJSON(requestParameters.newArticle),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArticleFromJSON(jsonValue));
    }

    /**
     * Create a new record
     */
    async articlesPost(requestParameters: ArticlesPostRequest, initOverrides?: RequestInit): Promise<Article> {
        const response = await this.articlesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async articlesSlugGetRaw(requestParameters: ArticlesSlugGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Article>> {
        if (requestParameters.slug === null || requestParameters.slug === undefined) {
            throw new runtime.RequiredError('slug','Required parameter requestParameters.slug was null or undefined when calling articlesSlugGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/articles/{slug}`.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters.slug))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArticleFromJSON(jsonValue));
    }

    /**
     */
    async articlesSlugGet(requestParameters: ArticlesSlugGetRequest, initOverrides?: RequestInit): Promise<Article> {
        const response = await this.articlesSlugGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
