/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Global,
    GlobalFromJSON,
    GlobalToJSON,
    NewGlobal,
    NewGlobalFromJSON,
    NewGlobalToJSON,
} from '../models';

export interface GlobalGetRequest {
    limit?: number;
    sort?: string;
    start?: number;
    ne?: string;
    lt?: string;
    lte?: string;
    gt?: string;
    gte?: string;
    contains?: string;
    containss?: string;
    _in?: Array<string>;
    nin?: Array<string>;
}

export interface GlobalPutRequest {
    newGlobal: NewGlobal;
}

/**
 * 
 */
export class GlobalApi extends runtime.BaseAPI {

    /**
     * Delete a single global record
     */
    async globalDeleteRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/global`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Delete a single global record
     */
    async globalDelete(initOverrides?: RequestInit): Promise<number> {
        const response = await this.globalDeleteRaw(initOverrides);
        return await response.value();
    }

    /**
     * Find all the global\'s records
     */
    async globalGetRaw(requestParameters: GlobalGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Global>>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['_limit'] = requestParameters.limit;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['_sort'] = requestParameters.sort;
        }

        if (requestParameters.start !== undefined) {
            queryParameters['_start'] = requestParameters.start;
        }

        if (requestParameters.ne !== undefined) {
            queryParameters['_ne'] = requestParameters.ne;
        }

        if (requestParameters.lt !== undefined) {
            queryParameters['_lt'] = requestParameters.lt;
        }

        if (requestParameters.lte !== undefined) {
            queryParameters['_lte'] = requestParameters.lte;
        }

        if (requestParameters.gt !== undefined) {
            queryParameters['_gt'] = requestParameters.gt;
        }

        if (requestParameters.gte !== undefined) {
            queryParameters['_gte'] = requestParameters.gte;
        }

        if (requestParameters.contains !== undefined) {
            queryParameters['_contains'] = requestParameters.contains;
        }

        if (requestParameters.containss !== undefined) {
            queryParameters['_containss'] = requestParameters.containss;
        }

        if (requestParameters._in) {
            queryParameters['_in'] = requestParameters._in;
        }

        if (requestParameters.nin) {
            queryParameters['_nin'] = requestParameters.nin;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/global`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GlobalFromJSON));
    }

    /**
     * Find all the global\'s records
     */
    async globalGet(requestParameters: GlobalGetRequest, initOverrides?: RequestInit): Promise<Array<Global>> {
        const response = await this.globalGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a single global record
     */
    async globalPutRaw(requestParameters: GlobalPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Global>> {
        if (requestParameters.newGlobal === null || requestParameters.newGlobal === undefined) {
            throw new runtime.RequiredError('newGlobal','Required parameter requestParameters.newGlobal was null or undefined when calling globalPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/global`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NewGlobalToJSON(requestParameters.newGlobal),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GlobalFromJSON(jsonValue));
    }

    /**
     * Update a single global record
     */
    async globalPut(requestParameters: GlobalPutRequest, initOverrides?: RequestInit): Promise<Global> {
        const response = await this.globalPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
