/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Homepage,
    HomepageFromJSON,
    HomepageToJSON,
    NewHomepage,
    NewHomepageFromJSON,
    NewHomepageToJSON,
} from '../models';

export interface HomepageGetRequest {
    limit?: number;
    sort?: string;
    start?: number;
    ne?: string;
    lt?: string;
    lte?: string;
    gt?: string;
    gte?: string;
    contains?: string;
    containss?: string;
    _in?: Array<string>;
    nin?: Array<string>;
}

export interface HomepagePutRequest {
    newHomepage: NewHomepage;
}

/**
 * 
 */
export class HomepageApi extends runtime.BaseAPI {

    /**
     * Delete a single homepage record
     */
    async homepageDeleteRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/homepage`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Delete a single homepage record
     */
    async homepageDelete(initOverrides?: RequestInit): Promise<number> {
        const response = await this.homepageDeleteRaw(initOverrides);
        return await response.value();
    }

    /**
     * Find all the homepage\'s records
     */
    async homepageGetRaw(requestParameters: HomepageGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Homepage>>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['_limit'] = requestParameters.limit;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['_sort'] = requestParameters.sort;
        }

        if (requestParameters.start !== undefined) {
            queryParameters['_start'] = requestParameters.start;
        }

        if (requestParameters.ne !== undefined) {
            queryParameters['_ne'] = requestParameters.ne;
        }

        if (requestParameters.lt !== undefined) {
            queryParameters['_lt'] = requestParameters.lt;
        }

        if (requestParameters.lte !== undefined) {
            queryParameters['_lte'] = requestParameters.lte;
        }

        if (requestParameters.gt !== undefined) {
            queryParameters['_gt'] = requestParameters.gt;
        }

        if (requestParameters.gte !== undefined) {
            queryParameters['_gte'] = requestParameters.gte;
        }

        if (requestParameters.contains !== undefined) {
            queryParameters['_contains'] = requestParameters.contains;
        }

        if (requestParameters.containss !== undefined) {
            queryParameters['_containss'] = requestParameters.containss;
        }

        if (requestParameters._in) {
            queryParameters['_in'] = requestParameters._in;
        }

        if (requestParameters.nin) {
            queryParameters['_nin'] = requestParameters.nin;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/homepage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HomepageFromJSON));
    }

    /**
     * Find all the homepage\'s records
     */
    async homepageGet(requestParameters: HomepageGetRequest, initOverrides?: RequestInit): Promise<Array<Homepage>> {
        const response = await this.homepageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a single homepage record
     */
    async homepagePutRaw(requestParameters: HomepagePutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Homepage>> {
        if (requestParameters.newHomepage === null || requestParameters.newHomepage === undefined) {
            throw new runtime.RequiredError('newHomepage','Required parameter requestParameters.newHomepage was null or undefined when calling homepagePut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/homepage`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NewHomepageToJSON(requestParameters.newHomepage),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HomepageFromJSON(jsonValue));
    }

    /**
     * Update a single homepage record
     */
    async homepagePut(requestParameters: HomepagePutRequest, initOverrides?: RequestInit): Promise<Homepage> {
        const response = await this.homepagePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
