/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    NewWriter,
    NewWriterFromJSON,
    NewWriterToJSON,
    Writer,
    WriterFromJSON,
    WriterToJSON,
} from '../models';

export interface WritersGetRequest {
    limit?: number;
    sort?: string;
    start?: number;
    ne?: string;
    lt?: string;
    lte?: string;
    gt?: string;
    gte?: string;
    contains?: string;
    containss?: string;
    _in?: Array<string>;
    nin?: Array<string>;
}

export interface WritersIdDeleteRequest {
    id: string;
}

export interface WritersIdGetRequest {
    id: string;
}

export interface WritersIdPutRequest {
    id: string;
    newWriter: NewWriter;
}

export interface WritersPostRequest {
    newWriter: NewWriter;
}

/**
 * 
 */
export class WriterApi extends runtime.BaseAPI {

    /**
     */
    async writersCountGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/writers/count`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async writersCountGet(initOverrides?: RequestInit): Promise<object> {
        const response = await this.writersCountGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async writersGetRaw(requestParameters: WritersGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Writer>>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['_limit'] = requestParameters.limit;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['_sort'] = requestParameters.sort;
        }

        if (requestParameters.start !== undefined) {
            queryParameters['_start'] = requestParameters.start;
        }

        if (requestParameters.ne !== undefined) {
            queryParameters['_ne'] = requestParameters.ne;
        }

        if (requestParameters.lt !== undefined) {
            queryParameters['_lt'] = requestParameters.lt;
        }

        if (requestParameters.lte !== undefined) {
            queryParameters['_lte'] = requestParameters.lte;
        }

        if (requestParameters.gt !== undefined) {
            queryParameters['_gt'] = requestParameters.gt;
        }

        if (requestParameters.gte !== undefined) {
            queryParameters['_gte'] = requestParameters.gte;
        }

        if (requestParameters.contains !== undefined) {
            queryParameters['_contains'] = requestParameters.contains;
        }

        if (requestParameters.containss !== undefined) {
            queryParameters['_containss'] = requestParameters.containss;
        }

        if (requestParameters._in) {
            queryParameters['_in'] = requestParameters._in;
        }

        if (requestParameters.nin) {
            queryParameters['_nin'] = requestParameters.nin;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/writers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WriterFromJSON));
    }

    /**
     */
    async writersGet(requestParameters: WritersGetRequest, initOverrides?: RequestInit): Promise<Array<Writer>> {
        const response = await this.writersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a record
     */
    async writersIdDeleteRaw(requestParameters: WritersIdDeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<number>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling writersIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/writers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Delete a record
     */
    async writersIdDelete(requestParameters: WritersIdDeleteRequest, initOverrides?: RequestInit): Promise<number> {
        const response = await this.writersIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async writersIdGetRaw(requestParameters: WritersIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Writer>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling writersIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/writers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WriterFromJSON(jsonValue));
    }

    /**
     */
    async writersIdGet(requestParameters: WritersIdGetRequest, initOverrides?: RequestInit): Promise<Writer> {
        const response = await this.writersIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a record
     */
    async writersIdPutRaw(requestParameters: WritersIdPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Writer>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling writersIdPut.');
        }

        if (requestParameters.newWriter === null || requestParameters.newWriter === undefined) {
            throw new runtime.RequiredError('newWriter','Required parameter requestParameters.newWriter was null or undefined when calling writersIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/writers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NewWriterToJSON(requestParameters.newWriter),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WriterFromJSON(jsonValue));
    }

    /**
     * Update a record
     */
    async writersIdPut(requestParameters: WritersIdPutRequest, initOverrides?: RequestInit): Promise<Writer> {
        const response = await this.writersIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new record
     */
    async writersPostRaw(requestParameters: WritersPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Writer>> {
        if (requestParameters.newWriter === null || requestParameters.newWriter === undefined) {
            throw new runtime.RequiredError('newWriter','Required parameter requestParameters.newWriter was null or undefined when calling writersPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/writers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewWriterToJSON(requestParameters.newWriter),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WriterFromJSON(jsonValue));
    }

    /**
     * Create a new record
     */
    async writersPost(requestParameters: WritersPostRequest, initOverrides?: RequestInit): Promise<Writer> {
        const response = await this.writersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
