{
 "title": "Loki v2 Web Analytics Dashboard",
 "description": "Loki version 2 showcase using JSON NGINX access logs.",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"${NGINX_LOGFILE}\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({filename=\"${NGINX_LOGFILE}\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum(rate({filename=\"${NGINX_LOGFILE}\"} | json | status >= 500 |__error__=\"\"[$__interval])) / (sum(rate({filename=\"${NGINX_LOGFILE}\"} | json | __error__=\"\"[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "% of requests by Googlebot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " sum(rate(({job=\"nginx_access_log\"} |= \"Googlebot\")[$__interval])) / (sum(rate(({job=\"nginx_access_log\"} |= \"Mozilla\")[10m])) / 100)"
    }
   ]
  },
  {
   "title": "Users right now",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=\"${NGINX_LOGFILE}\"} | json |  __error__=\"\" [5m])))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time({filename=\"${NGINX_LOGFILE}\"} | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval])",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Countries right now",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 9 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({filename=\"${NGINX_LOGFILE}\"} | json | __error__=\"\" [1m]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "{filename=\"${NGINX_LOGFILE}\"} | json | line_format \"request for {{.request_uri}} with HTTP status: {{.status}} \""
    }
   ]
  },
  { "title": "Request statistics over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "95th percentile of Request Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{filename=\"${NGINX_LOGFILE}\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (host) (max_over_time({filename=\"${NGINX_LOGFILE}\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({filename=\"${NGINX_LOGFILE}\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({filename=\"${NGINX_LOGFILE}\"} | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  { "title": "Acquisition and Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_user_agent) (count_over_time({filename=\"${NGINX_LOGFILE}\"} | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 30 },
   "targets": [
    {
     "expr": "topk(20, sum by (http_referer) (count_over_time({filename=\"${NGINX_LOGFILE}\"} | json | http_referer != \"\" | http_referer !~ \"appfelstrudel\" | http_referer !~ \"54.39.50.183\" |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_addr) (count_over_time({filename=\"${NGINX_LOGFILE}\"} | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Top Requested Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 36 },
   "targets": [
    {
     "expr": "topk(5,sum by (request_uri) (count_over_time({filename=\"${NGINX_LOGFILE}\"} | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  }
 ]
}