{
 "title": "richardwillis.info",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "query_result(nodejs_version_info)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(up{job=~\"$job\"})"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1h, 3h, 6h, 12h, 1d, 2d, 7d, 30d, 90d, 180d"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "query_result(nodejs_heap_size_total_bytes)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{instance=~\"$instance\",job=~\"$job\"}[$interval]) * 100)"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{version=~\"$version\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Failed Requests (5XX)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=~\"5.*\",version=~\"$version\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{version=~\"$version\"}[10m])) by (le, path))",
     "legendFormat": "p90 {{path}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{version=~\"$version\"}[10m])) by (le, path))",
     "legendFormat": "Median {{path}}"
    }
   ]
  },
  { "title": "Container Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes{version=~\"$version\",instance=~\"$instance\",job=~\"$job\"}) by (app, version)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Node.js Active Handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_active_handles{version=~\"$version\"}) by (app, type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}