{
 "title": "richardwillis.info",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "query_result(nodejs_version_info)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(up{job=~\"$job\"})"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "query_result(count by (version)(count_over_time(nodejs_heap_size_total_bytes[$__range])))"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "env", "label": "Environment", "query": "production,staging" }
  ]
 },
 "panels": [
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TTFB",
   "type": "graph",
   "description": "web-vitals metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_user_timing_ttfb_sum{version=~\"$version\"}[1h])) by (le, path, version)",
     "legendFormat": "{{path}} {{version}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{instance=~\"$instance\",job=~\"$job\"}[$__interval]) * 100)"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Requests per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{version=~\"$version\"}[1m])) by (app, version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Failed Requests (5XX)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=~\"5.*\",version=~\"$version\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=~\"4.*\",version=~\"$version\"}[1m])) by (app, code)",
     "legendFormat": "{{app}} - {{code}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{version=~\"$version\"}[10m])) by (le, path, version))",
     "legendFormat": "p90 {{path}} ({{version}})"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{version=~\"$version\"}[10m])) by (le, path, version))",
     "legendFormat": "Median {{path}} ({{version}})"
    }
   ]
  },
  {
   "title": "Overral Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{instance=~\"$instance\",version=~\"$version\"}[5m])) by (app, version)",
     "legendFormat": "{{app}} {{version}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\",version=~\"$version\"}[5m])) by (app, version) / sum(rate(http_request_duration_seconds_count{instance=~\"$instance\",job=~\"$job\",version=~\"$version\"}[5m])) by (app, version)",
     "legendFormat": "{{app}} - {{version}}"
    }
   ]
  },
  { "title": "Container Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_external_memory_bytes{version=~\"$version\",instance=~\"$instance\",job=~\"$job\"}) by (app, version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{version=~\"$version\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{app}} {{version}}"
    }
   ]
  },
  {
   "title": "Node.js Active Handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_active_handles{version=~\"$version\"}) by (app, type, version)",
     "legendFormat": "{{type}} {{version}}"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\", job=~\"$job\", version=~\"$version\"}",
     "legendFormat": "{{version}} "
    }
   ]
  }
 ]
}