version: '3.8'

services:
  plausible_db:
    image: postgres:13.3-alpine
    volumes:
      - plausible-db-data:/var/lib/postgresql/data
    networks:
      - plausible
    healthcheck:
      test: ['CMD', 'pg_isready']
    environment:
      - POSTGRES_DB=plausible
      - POSTGRES_USER_FILE=/run/secrets/plausible-postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/plausible-postgres-password
    secrets:
      - plausible-postgres-password
      - plausible-postgres-user
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - 'traefik.enable=false'

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    volumes:
      - plausible-event-data:/var/lib/clickhouse
      - plausible-etc-clickhouse-server:/etc/clickhouse-server
    networks:
      - plausible
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - 'traefik.enable=false'

  # plausible_geoip:
  #   image: maxmindinc/geoipupdate
  #   environment:
  #     - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
  #     - GEOIPUPDATE_FREQUENCY=168 # update every 7 days
  #   volumes:
  #     - plausible-geoip:/usr/share/GeoIP
  #   secrets:
  #     - plausible-geoupdate-account-id
  #     - plausible-geoupdate-license-key
  #   entrypoint:
  #     [
  #       '/bin/sh',
  #       '-c',
  #       'export GEOIPUPDATE_ACCOUNT_ID=$$(cat /run/secrets/plausible-geoupdate-account-id); export GEOIPUPDATE_LICENSE_KEY=$$(cat /run/secrets/plausible-geoupdate-license-key); source /usr/bin/entry.sh',
  #     ]
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     labels:
  #       - 'traefik.enable=false'

  plausible:
    image: plausible/analytics:master@sha256:adfc5f693e8d70d48b04fc17b009b2871b9ee23d9a349e606eab708e964d2a60
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    networks:
      - plausible
      - traefik-public
    environment:
      - CONFIG_DIR=/run/secrets
      # - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
      # - SMTP_HOST_SSL_ENABLED=true
      - SMTP_HOST_PORT=587
    # volumes:
    #   - plausible-geoip:/geoip:ro
    healthcheck:
      test:
        ['CMD', 'wget', '-q', '--tries=1', '--spider', 'http://localhost:8000']
    secrets:
      - source: plausible-admin-user-email
        target: /run/secrets/ADMIN_USER_EMAIL
      - source: plausible-admin-user-name
        target: /run/secrets/ADMIN_USER_NAME
      - source: plausible-admin-user-password
        target: /run/secrets/ADMIN_USER_PWD
      - source: plausible-base-url
        target: /run/secrets/BASE_URL
      - source: plausible-secret-key-base
        target: /run/secrets/SECRET_KEY_BASE
      - source: plausible-database-url
        target: /run/secrets/DATABASE_URL
      - source: plausible-mailer-email
        target: /run/secrets/MAILER_EMAIL
      - source: plausible-smtp-host-addr
        target: /run/secrets/SMTP_HOST_ADDR
      - source: plausible-smtp-user-name
        target: /run/secrets/SMTP_USER_NAME
      - source: plausible-smtp-user-pwd
        target: /run/secrets/SMTP_USER_PWD
      - source: plausible-google-client-id
        target: /run/secrets/GOOGLE_CLIENT_ID
      - source: plausible-google-client-secret
        target: /run/secrets/GOOGLE_CLIENT_SECRET
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.lbswarm=true'
        - 'traefik.http.routers.plausible.entrypoints=web'
        - 'traefik.http.routers.plausible.rule=Host(`plausible.docker-box.richardwillis.info`)'
        - 'traefik.http.services.plausible-service.loadbalancer.server.port=8000'
        - 'traefik.http.middlewares.plausible-redirectscheme.redirectscheme.permanent=true'
        - 'traefik.http.middlewares.plausible-redirectscheme.redirectscheme.scheme=https'
        - 'traefik.http.routers.plausible.middlewares=plausible-redirectscheme'
        - 'traefik.http.routers.plausible-secure.entrypoints=websecure'
        - 'traefik.http.routers.plausible-secure.rule=Host(`plausible.docker-box.richardwillis.info`)'
        - 'traefik.http.routers.plausible-secure.tls.certresolver=letsencrypt'

networks:
  traefik-public:
    external: true
  plausible:
    driver: overlay
    attachable: true

secrets:
  plausible-admin-user-email:
    external: true
  plausible-admin-user-name:
    external: true
  plausible-admin-user-password:
    external: true
  plausible-base-url:
    external: true
  plausible-secret-key-base:
    external: true
  plausible-postgres-user:
    external: true
  plausible-postgres-password:
    external: true
  plausible-database-url:
    external: true
  plausible-geoupdate-account-id:
    external: true
  plausible-geoupdate-license-key:
    external: true
  plausible-mailer-email:
    external: true
  plausible-smtp-host-addr:
    external: true
  plausible-smtp-user-name:
    external: true
  plausible-smtp-user-pwd:
    external: true
  plausible-google-client-id:
    external: true
  plausible-google-client-secret:
    external: true

volumes:
  plausible-db-data:
  plausible-event-data:
  plausible-etc-clickhouse-server:
