/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AboutpageSeo
 */
export interface AboutpageSeo {
    /**
     * 
     * @type {string}
     * @memberof AboutpageSeo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AboutpageSeo
     */
    metaTitle: string;
    /**
     * 
     * @type {string}
     * @memberof AboutpageSeo
     */
    metaDescription: string;
    /**
     * 
     * @type {object}
     * @memberof AboutpageSeo
     */
    shareImage?: object;
}

export function AboutpageSeoFromJSON(json: any): AboutpageSeo {
    return AboutpageSeoFromJSONTyped(json, false);
}

export function AboutpageSeoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AboutpageSeo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'metaTitle': json['metaTitle'],
        'metaDescription': json['metaDescription'],
        'shareImage': !exists(json, 'shareImage') ? undefined : json['shareImage'],
    };
}

export function AboutpageSeoToJSON(value?: AboutpageSeo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'metaTitle': value.metaTitle,
        'metaDescription': value.metaDescription,
        'shareImage': value.shareImage,
    };
}


