/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GlobalDefaultSeo,
    GlobalDefaultSeoFromJSON,
    GlobalDefaultSeoFromJSONTyped,
    GlobalDefaultSeoToJSON,
} from './';

/**
 * 
 * @export
 * @interface Global
 */
export interface Global {
    /**
     * 
     * @type {string}
     * @memberof Global
     */
    id: string;
    /**
     * 
     * @type {object}
     * @memberof Global
     */
    favicon?: object;
    /**
     * 
     * @type {string}
     * @memberof Global
     */
    siteName: string;
    /**
     * 
     * @type {GlobalDefaultSeo}
     * @memberof Global
     */
    defaultSeo: GlobalDefaultSeo;
}

export function GlobalFromJSON(json: any): Global {
    return GlobalFromJSONTyped(json, false);
}

export function GlobalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Global {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'favicon': !exists(json, 'favicon') ? undefined : json['favicon'],
        'siteName': json['siteName'],
        'defaultSeo': GlobalDefaultSeoFromJSON(json['defaultSeo']),
    };
}

export function GlobalToJSON(value?: Global | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'favicon': value.favicon,
        'siteName': value.siteName,
        'defaultSeo': GlobalDefaultSeoToJSON(value.defaultSeo),
    };
}


