/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GlobalDefaultSeo,
    GlobalDefaultSeoFromJSON,
    GlobalDefaultSeoFromJSONTyped,
    GlobalDefaultSeoToJSON,
    HomepageHero,
    HomepageHeroFromJSON,
    HomepageHeroFromJSONTyped,
    HomepageHeroToJSON,
} from './';

/**
 * 
 * @export
 * @interface Homepage
 */
export interface Homepage {
    /**
     * 
     * @type {string}
     * @memberof Homepage
     */
    id: string;
    /**
     * 
     * @type {GlobalDefaultSeo}
     * @memberof Homepage
     */
    seo?: GlobalDefaultSeo;
    /**
     * 
     * @type {HomepageHero}
     * @memberof Homepage
     */
    hero: HomepageHero;
}

export function HomepageFromJSON(json: any): Homepage {
    return HomepageFromJSONTyped(json, false);
}

export function HomepageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Homepage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'seo': !exists(json, 'seo') ? undefined : GlobalDefaultSeoFromJSON(json['seo']),
        'hero': HomepageHeroFromJSON(json['hero']),
    };
}

export function HomepageToJSON(value?: Homepage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'seo': GlobalDefaultSeoToJSON(value.seo),
        'hero': HomepageHeroToJSON(value.hero),
    };
}


