/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewArticle
 */
export interface NewArticle {
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    excerpt?: string;
    /**
     * 
     * @type {Date}
     * @memberof NewArticle
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticle
     */
    updatedBy?: string;
}

export function NewArticleFromJSON(json: any): NewArticle {
    return NewArticleFromJSONTyped(json, false);
}

export function NewArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewArticle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'content': json['content'],
        'slug': json['slug'],
        'category': !exists(json, 'category') ? undefined : json['category'],
        'author': !exists(json, 'author') ? undefined : json['author'],
        'excerpt': !exists(json, 'excerpt') ? undefined : json['excerpt'],
        'publishedAt': !exists(json, 'published_at') ? undefined : (new Date(json['published_at'])),
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
        'updatedBy': !exists(json, 'updated_by') ? undefined : json['updated_by'],
    };
}

export function NewArticleToJSON(value?: NewArticle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'content': value.content,
        'slug': value.slug,
        'category': value.category,
        'author': value.author,
        'excerpt': value.excerpt,
        'published_at': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'created_by': value.createdBy,
        'updated_by': value.updatedBy,
    };
}


