/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewArticleComment
 */
export interface NewArticleComment {
    /**
     * 
     * @type {string}
     * @memberof NewArticleComment
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof NewArticleComment
     */
    body?: string;
}

export function NewArticleCommentFromJSON(json: any): NewArticleComment {
    return NewArticleCommentFromJSONTyped(json, false);
}

export function NewArticleCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewArticleComment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'author': !exists(json, 'author') ? undefined : json['author'],
        'body': !exists(json, 'body') ? undefined : json['body'],
    };
}

export function NewArticleCommentToJSON(value?: NewArticleComment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author': value.author,
        'body': value.body,
    };
}


