/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewCategory
 */
export interface NewCategory {
    /**
     * 
     * @type {string}
     * @memberof NewCategory
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NewCategory
     */
    slug: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewCategory
     */
    articles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof NewCategory
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof NewCategory
     */
    updatedBy?: string;
}

export function NewCategoryFromJSON(json: any): NewCategory {
    return NewCategoryFromJSONTyped(json, false);
}

export function NewCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewCategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'slug': json['slug'],
        'articles': !exists(json, 'articles') ? undefined : json['articles'],
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
        'updatedBy': !exists(json, 'updated_by') ? undefined : json['updated_by'],
    };
}

export function NewCategoryToJSON(value?: NewCategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'slug': value.slug,
        'articles': value.articles,
        'created_by': value.createdBy,
        'updated_by': value.updatedBy,
    };
}


