/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewComment
 */
export interface NewComment {
    /**
     * 
     * @type {string}
     * @memberof NewComment
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof NewComment
     */
    body?: string;
    /**
     * 
     * @type {string}
     * @memberof NewComment
     */
    article?: string;
    /**
     * 
     * @type {Date}
     * @memberof NewComment
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof NewComment
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof NewComment
     */
    updatedBy?: string;
}

export function NewCommentFromJSON(json: any): NewComment {
    return NewCommentFromJSONTyped(json, false);
}

export function NewCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewComment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'author': !exists(json, 'author') ? undefined : json['author'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'article': !exists(json, 'article') ? undefined : json['article'],
        'publishedAt': !exists(json, 'published_at') ? undefined : (new Date(json['published_at'])),
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
        'updatedBy': !exists(json, 'updated_by') ? undefined : json['updated_by'],
    };
}

export function NewCommentToJSON(value?: NewComment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author': value.author,
        'body': value.body,
        'article': value.article,
        'published_at': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'created_by': value.createdBy,
        'updated_by': value.updatedBy,
    };
}


