/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GlobalDefaultSeo,
    GlobalDefaultSeoFromJSON,
    GlobalDefaultSeoFromJSONTyped,
    GlobalDefaultSeoToJSON,
    HomepageHero,
    HomepageHeroFromJSON,
    HomepageHeroFromJSONTyped,
    HomepageHeroToJSON,
} from './';

/**
 * 
 * @export
 * @interface NewHomepage
 */
export interface NewHomepage {
    /**
     * 
     * @type {GlobalDefaultSeo}
     * @memberof NewHomepage
     */
    seo?: GlobalDefaultSeo;
    /**
     * 
     * @type {HomepageHero}
     * @memberof NewHomepage
     */
    hero: HomepageHero;
    /**
     * 
     * @type {string}
     * @memberof NewHomepage
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof NewHomepage
     */
    updatedBy?: string;
}

export function NewHomepageFromJSON(json: any): NewHomepage {
    return NewHomepageFromJSONTyped(json, false);
}

export function NewHomepageFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewHomepage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'seo': !exists(json, 'seo') ? undefined : GlobalDefaultSeoFromJSON(json['seo']),
        'hero': HomepageHeroFromJSON(json['hero']),
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
        'updatedBy': !exists(json, 'updated_by') ? undefined : json['updated_by'],
    };
}

export function NewHomepageToJSON(value?: NewHomepage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'seo': GlobalDefaultSeoToJSON(value.seo),
        'hero': HomepageHeroToJSON(value.hero),
        'created_by': value.createdBy,
        'updated_by': value.updatedBy,
    };
}


