/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewProject
 */
export interface NewProject {
    /**
     * 
     * @type {string}
     * @memberof NewProject
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NewProject
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof NewProject
     */
    tags: string;
    /**
     * 
     * @type {string}
     * @memberof NewProject
     */
    repoUrl: string;
    /**
     * 
     * @type {Date}
     * @memberof NewProject
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof NewProject
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof NewProject
     */
    updatedBy?: string;
}

export function NewProjectFromJSON(json: any): NewProject {
    return NewProjectFromJSONTyped(json, false);
}

export function NewProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewProject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'tags': json['tags'],
        'repoUrl': json['repoUrl'],
        'publishedAt': !exists(json, 'published_at') ? undefined : (new Date(json['published_at'])),
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
        'updatedBy': !exists(json, 'updated_by') ? undefined : json['updated_by'],
    };
}

export function NewProjectToJSON(value?: NewProject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'tags': value.tags,
        'repoUrl': value.repoUrl,
        'published_at': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'created_by': value.createdBy,
        'updated_by': value.updatedBy,
    };
}


