/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewWriter
 */
export interface NewWriter {
    /**
     * 
     * @type {string}
     * @memberof NewWriter
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewWriter
     */
    articles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof NewWriter
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof NewWriter
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof NewWriter
     */
    updatedBy?: string;
}

export function NewWriterFromJSON(json: any): NewWriter {
    return NewWriterFromJSONTyped(json, false);
}

export function NewWriterFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewWriter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'articles': !exists(json, 'articles') ? undefined : json['articles'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'createdBy': !exists(json, 'created_by') ? undefined : json['created_by'],
        'updatedBy': !exists(json, 'updated_by') ? undefined : json['updated_by'],
    };
}

export function NewWriterToJSON(value?: NewWriter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'articles': value.articles,
        'email': value.email,
        'created_by': value.createdBy,
        'updated_by': value.updatedBy,
    };
}


