_id: 344eb780-deab-11eb-9c79-1504fc878584
slug: monitor-dokku-server-prometheus-loki-grafana
name: Ray
message: >-
  Thanks, really awesome tutorial! Saved me a lot of time!


  Here are a few comments for newcomers.

  - Idk if it's a typo or just letsencrypt extension has been updated since
  then. But everywhere in the article need to fix

  `dokku letsencrypt <service>` to `dokku letsencrypt:enable <service>`

  - I didn't need nginx logs so I skipped "Monitor Nginx Access Logs" part. But
  what I really needed is collecting logs from docker containers and showing
  them in grafana. You can achieve this by following next 3 steps:
    1) Extend config for promtail: see first comment from [this gist](https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460) after line `- job_name: containers`.
    2) Map `/var/lib/docker/containers` dir to docker promtail container:
      `dokku storage:mount promtail /var/lib/docker/containers:/var/lib/docker/containers`
    3) Add docker options as it's described in the github gist above:
    ```
    dokku docker-options:add my-app deploy '--log-opt tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"'
    dokku docker-options:remove my-app deploy '--log-driver json-file'
    ```
    After all don't forgret to rebuild your app and promtail to apply changes.
    ```
    dokku ps:rebuild my-app
    dokku ps:rebuild promtail
    ```
date: 1625611246662
