name: Delete Preview Site

on:
  pull_request:
    types: [closed]

jobs:
  delete-preview-site:
    runs-on: ubuntu-20.04
    name: Delete Preview Site
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: github.actor != 'dependabot[bot]'
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: AWS Static Stack
        uses: badsyntax/github-action-aws-static-stack@v0.0.8
        if: github.actor != 'dependabot[bot]'
        with:
          cf-stack-name: 'richardwillis-info-cloudfront-s3'
          cf-template: './cloudformation/cloudformation-s3bucket-stack.yml'
          cf-apply-change-set: ${{ github.event_name != 'repository_dispatch' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          aws-region: 'us-east-1'
          s3-bucket-name: 'richardwillis.info-us-east-1'
          s3-allowed-origins: 'https://richardwillis.info, https://assets.richardwillis.inf'
          cloudfront-root-hosts: 'assets.richardwillis.info, richardwillis.info'
          cloudfront-preview-hosts: '*.preview.richardwillis.info'
          cloudfront-default-root-object: 'index'
          certificate-arn: ${{ secrets.ROOT_DOMAIN_CERTIFICATE_ARN }}
          src-dir: './out'
          static-files-glob: '{_next,site-assets}/**/*'
          lambda-version: '1.0.1'
          delete-preview-site-on-pr-close: true
          comment-template: '.github/pr-comment-template.hbs'
